spring.application.name=hotel-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_system
spring.datasource.username=postgres
spring.datasource.password=HMSpass!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect